name: 'Sous GraphQL'
description: 'A recipe that contains modules and configuration for Sous default GraphQL configuration.'
type: 'Site'
install:
  - graphql
  - graphql_compose
  - graphql_compose_edges
  - graphql_compose_fragments
  - graphql_compose_menus
  - graphql_compose_routes
  - graphql_compose_views
  - graphql_export
  - simple_oauth
  - view_unpublished
config:
  import:
    graphql: '*'
    graphql_compose: '*'
    graphql_compose_edges: '*'
    graphql_compose_fragments: '*'
    graphql_compose_menus: '*'
    graphql_compose_routes: '*'
    graphql_compose_views: '*'
    graphql_export: '*'
    simple_oauth: '*'
  actions:
    graphql_compose.settings:
      simple_config_update:
        settings.inflector_singularize: false
        settings.simple_queries: false
        settings.simple_unions: false
    simple_oauth.settings:
      simple_config_update:
        public_key: ../keys/public.key
        private_key: ../keys/private.key
